import { sign, getPublicKey, hashes } from '@noble/secp256k1';
import { sha256 } from '@noble/hashes/sha2.js';
import { hmac } from '@noble/hashes/hmac.js';
import { serializeDecisionIntent } from './src/payload.js';
hashes.sha256 = sha256;
hashes.hmacSha256 = (k,m)=>hmac(sha256,k,m);
const sk = new Uint8Array(Array.from({length:32},(_,i)=>i+1));
const pk = getPublicKey(sk, true);
const vaultId = '0x1234';
const epoch = 100n, targetWeightMilli = 500n, timestampMs = 1744038900000n;
const inputsHash = sha256(new TextEncoder().encode('test-inputs'));
const msg = serializeDecisionIntent({ vaultId, epoch, targetWeightMilli, inputsHash, timestampMs });
const digest = sha256(msg);
const sig = sign(digest, sk, { prehash:false });
const hex = (b)=>Buffer.from(b).toString('hex');
console.log('PK_COMPRESSED =', hex(pk));
console.log('INPUTS_HASH   =', hex(inputsHash));
console.log('MSG_BYTES     =', hex(msg));
console.log('SIGNATURE     =', hex(sig), '(len', sig.length + ')');
